### ISSUE TITLE
 connect: cannot assign requested address

### ISSUE THREAD

**Issue by Sharda-Borse** [influxdata/inch#24]
Hi ,
inch -v -c 8 -b 100 -t 200 -db TestData -host http://18.188.109.199:8086 -f 1 -p 50000

So its should insert 10,000,000 records
after 9,000,000 records its throwing error like "Post http://18.188.109.199:8086/write?db=TestData&precision=ns&consistency=any: dial tcp 18.188.109.199:8086: connect: cannot assign requested address" but inserting all the 10,000,000 records in db. 

came across below thread while searching for error : 
https://github.com/golang/go/issues/16012
Thanks,
Sharda

**Comment by cmd-influx** [comment]
(Note: Cleaning up old issues.)

The command above is working with OSS 1.7.8 (currently available).

Without details, I would worry about memory and cache settings.  We have switched to TSI index from TSM where TSM must fit in memory while TSI can spill over to disk.
